### ISSUE TITLE
use callback in object

### ISSUE THREAD

**Issue by gsouf** [asvd/jailed#29]
When I put a callback in a config object, it got deleted from the object.

Example:

```js
var plugin = new jailed.Plugin(jsFile, {
    "test": function(config){
        console.log(config);
    }
});
```

When I jail this script: 

```js
application.remote.test(function(){
    // ...
});
``` 

It outputs ``[Function]`` it's ok

Now with this file 

```js
application.remote.test({
    "foo": "foo",
    "bar": function(){
        // ...
    }
});
``` 

It outputs ``{ foo: 'foo' }`` bar is not exported

**Comment by asvd** [comment]
You are right, this way of providing callbacks is not supported. But you can provide the callback as a separate argument, like this:

```js
var data = { foo: 'foo' };
var callback = function() { ... };
application.remote.test(data, callback);
```

In this case the callback is preserved and can be invoked from the other side.

But if an argument is not a function, but an object, it is serialized, and all the functions are thrown away.

Would it work for you, if you provide the callback as a separate argument? Or do you think that the callbacks should be extracted from the objects for some reason?

**Comment by gsouf** [comment]
Thank for your attention,

I could put the callback in the function arguments, but there are several events I have to deal with, that means some callbacks that can be possiblely passed to the function. And that can grows as the application grows and the function signature would become very complex. 
The second easy way would be to use an object returned by the function, with some callback setter, but as you state in the doc, remote function dont return anything.

I probably can workarround it, but that would be awesome if I could use functions as config values in an object ! 

Do you think that can be safely supported by jailed ?

**Comment by asvd** [comment]
> Do you think that can be safely supported by jailed ?

This sounds like possible, but far too complex and over-designed. Currently I have a feeling that your case can be solved in a clean way using the existing capabilities of jailed. Then I would maybe update the docs somehow to explain such a case.

Returned values are ignored due to the fact that exported methods are invoked asynchronously. But you can give a callback which will process the result as an argument, this should be pretty similar, as long as you need to pass the data as a result.

Next there are two more options:
- Instead of invoking the given callback, you can provide a string identifier for an event happened, and handle it respectively on the other side;
- You can export all possible event type handlers during the initialization, so that instead of invoking the provided callback, application would invoke the respective method exported from the plugin side.

Would it work?

**Comment by gsouf** [comment]
Well, that will make things more complex to write and to use but I can deal with it! Once documented that would be ok.

Thank you
